
Vagrant.configure("2") do |config|
 
  config.vm.box = "centos/7"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.56.2"
  config.vm.synced_folder ".vagrant", "/vagrant"
  config.vm.synced_folder "playbooks/vars", "/vagrant"
  config.vm.synced_folder "provision.sh", "/vagrant"
  config.vm.synced_folder "Vagrantfile", "/vagrant"
  config.vm.synced_folder "Vagrantfile", "/vagrant"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", path: "provision.sh"
end

